repositories:
  - name: prometheus
    url: https://prometheus-community.github.io/helm-charts


releases:
- name: demochart
  namespace: dev
  chart: ./demochart
  installed: false

- name: demochart2
  namespace: prod
  chart: ./demochart2
  installed: false

- name: prometheus
  namespace: prometheus
  chart: prometheus/prometheus
  set:
    - name: rbac.create
      value: false
  installed: false

- name: prometheus-prod
  namespace: prod
  chart: prometheus/prometheus
  installed: false
